<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Vitamin_bayi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Vitamin_bayi_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'vitamin_bayi/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'vitamin_bayi/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'vitamin_bayi/index.html';
            $config['first_url'] = base_url() . 'vitamin_bayi/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Vitamin_bayi_model->total_rows($q);
        $vitamin_bayi = $this->Vitamin_bayi_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'vitamin_bayi_data' => $vitamin_bayi,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('vitamin_bayi/tbl_vitamin_bayi_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Vitamin_bayi_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_vitamin' => $row->id_vitamin,
		'vit_A' => $row->vit_A,
	    );
            $this->load->view('vitamin_bayi/tbl_vitamin_bayi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('vitamin_bayi'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('vitamin_bayi/create_action'),
	    'id_vitamin' => set_value('id_vitamin'),
	    'vit_A' => set_value('vit_A'),
	);
        $this->load->view('vitamin_bayi/tbl_vitamin_bayi_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'vit_A' => $this->input->post('vit_A',TRUE),
	    );

            $this->Vitamin_bayi_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('vitamin_bayi'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Vitamin_bayi_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('vitamin_bayi/update_action'),
		'id_vitamin' => set_value('id_vitamin', $row->id_vitamin),
		'vit_A' => set_value('vit_A', $row->vit_A),
	    );
            $this->load->view('vitamin_bayi/tbl_vitamin_bayi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('vitamin_bayi'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_vitamin', TRUE));
        } else {
            $data = array(
		'vit_A' => $this->input->post('vit_A',TRUE),
	    );

            $this->Vitamin_bayi_model->update($this->input->post('id_vitamin', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('vitamin_bayi'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Vitamin_bayi_model->get_by_id($id);

        if ($row) {
            $this->Vitamin_bayi_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('vitamin_bayi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('vitamin_bayi'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('vit_A', 'vit a', 'trim|required');

	$this->form_validation->set_rules('id_vitamin', 'id_vitamin', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Vitamin_bayi.php */
/* Location: ./application/controllers/Vitamin_bayi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-21 05:20:48 */
/* http://harviacode.com */