<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Biodata_ibu_hamil_model extends CI_Model
{

    public $table = 'tbl_biodata_ibu_hamil';
    public $id = 'id_ibu_hamil';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ibu_hamil', $q);
	$this->db->or_like('no_urut', $q);
	$this->db->or_like('no_indek', $q);
	$this->db->or_like('id_nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('id_umur', $q);
	$this->db->or_like('hamil_ke', $q);
	$this->db->or_like('bb_tb', $q);
	$this->db->or_like('lila_mt', $q);
	$this->db->or_like('hb_goldar', $q);
	$this->db->or_like('tensi', $q);
	$this->db->or_like('id_resiko', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ibu_hamil', $q);
	$this->db->or_like('no_urut', $q);
	$this->db->or_like('no_indek', $q);
	$this->db->or_like('id_nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('id_umur', $q);
	$this->db->or_like('hamil_ke', $q);
	$this->db->or_like('bb_tb', $q);
	$this->db->or_like('lila_mt', $q);
	$this->db->or_like('hb_goldar', $q);
	$this->db->or_like('tensi', $q);
	$this->db->or_like('id_resiko', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Biodata_ibu_hamil_model.php */
/* Location: ./application/models/Biodata_ibu_hamil_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-21 04:50:41 */
/* http://harviacode.com */