<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Imunisasi_bayi_model extends CI_Model
{

    public $table = 'tbl_imunisasi_bayi';
    public $id = 'id_imunisasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_imunisasi', $q);
	$this->db->or_like('hb-7hr', $q);
	$this->db->or_like('polio 1', $q);
	$this->db->or_like('polio 2', $q);
	$this->db->or_like('polio 3', $q);
	$this->db->or_like('polio 4', $q);
	$this->db->or_like('campak', $q);
	$this->db->or_like('IDL', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_imunisasi', $q);
	$this->db->or_like('hb-7hr', $q);
	$this->db->or_like('polio 1', $q);
	$this->db->or_like('polio 2', $q);
	$this->db->or_like('polio 3', $q);
	$this->db->or_like('polio 4', $q);
	$this->db->or_like('campak', $q);
	$this->db->or_like('IDL', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Imunisasi_bayi_model.php */
/* Location: ./application/models/Imunisasi_bayi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-21 05:21:07 */
/* http://harviacode.com */