<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tahun_pertama_bayi_model extends CI_Model
{

    public $table = 'tbl_tahun_pertama_bayi';
    public $id = 'id_tahun_pertama';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_tahun_pertama', $q);
	$this->db->or_like('jan', $q);
	$this->db->or_like('feb', $q);
	$this->db->or_like('maret', $q);
	$this->db->or_like('april', $q);
	$this->db->or_like('mei', $q);
	$this->db->or_like('juni', $q);
	$this->db->or_like('july', $q);
	$this->db->or_like('agst', $q);
	$this->db->or_like('sept', $q);
	$this->db->or_like('okt', $q);
	$this->db->or_like('nov', $q);
	$this->db->or_like('des', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_tahun_pertama', $q);
	$this->db->or_like('jan', $q);
	$this->db->or_like('feb', $q);
	$this->db->or_like('maret', $q);
	$this->db->or_like('april', $q);
	$this->db->or_like('mei', $q);
	$this->db->or_like('juni', $q);
	$this->db->or_like('july', $q);
	$this->db->or_like('agst', $q);
	$this->db->or_like('sept', $q);
	$this->db->or_like('okt', $q);
	$this->db->or_like('nov', $q);
	$this->db->or_like('des', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tahun_pertama_bayi_model.php */
/* Location: ./application/models/Tahun_pertama_bayi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-21 05:16:11 */
/* http://harviacode.com */